version: '3'
 
services:
  my-queue:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
 
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres123
      POSTGRES_DB: sampledb
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  python_env:
    restart: always
    build: .
    container_name: 'python_env'
    working_dir: '/var/work'
    tty: true
    ports:
      - 8888:8888
    volumes:
      - ./work:/var/work


volumes:
  rabbitmq-data:
  postgres:

# RabbitMQ 起動確認済み
# version: '3'
 
# services:
#   my-queue:
#     container_name: rabbitmq
#     image: rabbitmq:3.8.9-management
#     ports:
#       - '5672:5672'
#       - '15672:15672'
#     volumes:
#       - ./rabbitmq-data:/var/lib/rabbitmq
 
# volumes:
#   rabbitmq-data:


# Postgresql 起動確認済み
# version: '3'
 
# services:
#   postgres:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       PGPASSWORD: postgres123
#       POSTGRES_DB: sampledb
#       TZ: "Asia/Tokyo"
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres:/var/lib/postgresql/data

# volumes:
#   postgres: